version: '3.9'

services:
  app:
    build: .
    environment:
      SECRET_KEY: "123"
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://bulterier04:123@db:5432/notes_db"
      FLASK_ENV: "development"
      PORT: 5432
      APP_HOST: 0.0.0.0
      APP_PORT: 5000
    depends_on:
      - db
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - "5000:5000"

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: bulterier04
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: notes_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  static_volume:
  pg_data: